### ISSUE TITLE
Gitit does not install on Windows

### ISSUE THREAD

**Issue by jgm** [jgm/gitit#251]
<pre>
<b>What steps will reproduce the problem?</b>
1. On Windows 7, follow instructions at http://gitit.net/Installing
2. In the step 'cabal install gitit' many packages install ok, but a few don't, causing gitit not to be built/installed

<b>What is the expected output? What do you see instead?</b>
Expected output is a successful install of gitit, instead I see (when running cabal install gitit a second time):
C:\Users\sreiz&gt;cabal install gitit
Resolving dependencies...
Configuring unix-2.4.0.2...
cabal: The package has a './configure' script. This requires a Unix
compatibility toolchain such as MinGW+MSYS or Cygwin.
cabal: Error: some packages failed to install:
cautious-file-0.1.5 depends on unix-2.4.0.2 which failed to install.
gitit-0.7.3.8 depends on unix-2.4.0.2 which failed to install.
unix-2.4.0.2 failed during the configure step. The exception was:
ExitFailure 1

<b>What version of the product are you using? On what operating system?</b>
Install attempted with latest versions on 6-aug-2010 (Haskell platform 2010.2.0.0, PortableGit-1.7.1-preview20100612.7z )

<b>Please provide any additional information below.</b>
I don't have enough Haskell knowledge to know if this is a serious issue, but if it is it would be good to update the info on gitit.net to make clear it won't install on Windows.

Google Code Info:
Issue #: 108
Author: steven.r...@gmail.com
Created On: 2010-08-06T14:26:19.000Z
Closed On: 
</pre>

**Comment by mikeholler** [comment]
Any updates here? Does gitit work on windows?

**Comment by odomanov** [comment]
As of Nov 2019, I managed to compile it on Win 10, Haskell Platform, but I had to set the flag:
`stack install --flag sendfile:portable`
Otherwise there was a problem with Win32 package, which I failed to cope with.
