### ISSUE TITLE
Inline iframes

### ISSUE THREAD

**Issue by jb55** [jgm/gitit#284]
Is there a way to modify pandoc to allow inline iframes? I'm looking to embed youtube videos in the wiki but it seems to just ignore the tag.

**Comment by lenzls** [comment]
Hello,
I'm having this exact same problem and I wonder if there is a solution.

My wiki page:
```
---
format: markdown
...

<strong>something</strong>
<iframe src="https://www.google.com">Fallback content</iframe>
<i>test</i>
```

In the resulting HTML, the iframe is omitted:
```
<p><strong>something</strong>
Fallback content
<i>test</i></p>
```

I have 
```
xss-sanitize: no
```
in my `gitit.config` and disabled all my plugins.

----

It looks like in pandoc2, the `readerParseRaw` parameter was removed in favour of the [`raw_html` extension](https://pandoc.org/MANUAL.html#extension-raw_html).
```
[0] $> pandoc -f markdown -t html test.md
<p><strong>something</strong> <iframe src="https://www.google.com">Fallback content</iframe> <i>test</i></p>

[0] $> pandoc -f html -t html test.md
--- format: markdown ... <strong>something</strong>
Fallback content
<em>test</em>

[0] $> pandoc -f html+raw_html -t html test.md
--- format: markdown ... <strong>something</strong>
<iframe src="https://www.google.com">
Fallback content
</iframe>
<em>test</em>
```

I'd be thankful for all hints how to get this behaviour in gitit.
