### ISSUE TITLE
Feature request: Make page extension configurable.

### ISSUE THREAD

**Issue by jplona** [jgm/gitit#298]
I have a repository full of markdown files with extensions such as 'md', 'mkdn', 'markdown', etc.  I can easily rename them all to '.page', but then other tools (such as vim) won't recognize them by default.

Allowing the user to configure a map from extension to format, or even just having a sane default mapping would be enough to satisfy this need.

**Comment by smari** [comment]
I would also like this feature, as I have the wiki's git archive cloned to my Android and am using JotterPadX there to edit the files -- but JotterPadX won't allow arbitrary file extensions. Therefore I'm stuck with manually moving files created in that before pushing them to git, which is a pretty messy workflow.

**Comment by wcaleb** [comment]
@smari If you are willing to accept the remaining bugs, merging #445 may work for you.

**Comment by smari** [comment]
Hi! That would work, except I'm installing from Caleb and don't really want to be mucking about in the code. I'd rather just be a bit annoying. :-)

**Comment by wcaleb** [comment]
I assume you mean "installing from Cabal"? ;-)

**Comment by smari** [comment]
Uh, yes. Sorry, that was a brainfart. Or perhaps I ment Kobol? :-)

**Comment by baco** [comment]
When are #445 commits (7be7dfc and d98c60c) merging into master?

**Comment by jgm** [comment]
I've just merged #445.
