### ISSUE TITLE
Could not read mime types file: /etc/mime.types

### ISSUE THREAD

**Issue by lottspot** [jgm/gitit#336]
[james@ArchServ wikitest]$ gitit -f gitit.conf
Could not read mime types file: /etc/mime.types
/etc/mime.types: openBinaryFile: does not exist (No such file or directory)

gitit.conf:

```
port: 5001
wiki-title: Wiki
repository-type: Git
repository-path: wikidata
require-authentication: modify
authentication-method: form
user-file: gitit-users
session-timeout: 60
static-dir: static
default-page-type: Markdown
math: MathML
show-lhs-bird-tracks: no
templates-dir: templates
log-file: gitit.log
log-level: WARNING
front-page: Front Page
no-delete: Front Page, Help
no-edit: Help
default-summary:
table-of-contents: yes
plugins:
use-cache: no
cache-dir: cache
max-upload-size: 100K
max-page-size: 100K
debug-mode: no
compress-responses: no
mime-types-file: /etc/nginx/mime.types
use-recaptcha: no
recaptcha-private-key:
recaptcha-public-key:
access-question:
access-question-answers:
rpx-domain:
rpx-key:
mail-command: sendmail %s
reset-password-message:
  > From: nobody@$hostname$
  > To: $useremail$
  > Subject: Wiki password reset
  >
  > Dear $username$:
  > 
  > To reset your password, please follow the link below:
  > http://$hostname$:$port$$resetlink$
  > 
  > Yours sincerely,
  > The Wiki Master
use-feed: n
base-url:
absolute-urls: no
feed-days: 14
feed-refresh-time: 60
pdf-export: no
pandoc-user-data:
xss-sanitize: yes
```

**Comment by ickc** [comment]
Hi, I receive the same error message. I installed gitit on OS X El Capitan and in a fresh installation. The gitit is being put in `~/.local/bin/` and I added it in the `PATH`. I ran

```bash
gitit --print-default-config > my.conf
gitit -f my.conf
```

And even if I didn't change the my.conf at all, it will still gives the error message:

> Could not read mime types file: /etc/mime.types
/etc/mime.types: openFile: does not exist (No such file or directory)
Using defaults instead.

**Comment by jgm** [comment]
+++ ickc [Apr 18 16 19:21 ]:
>   Hi, I receive the same error message. I installed gitit on OS X El
>   Capitan and in a fresh installation. The gitit is being put in
>   ~/.local/bin/ and I added it in the PATH. I ran
>
>gitit --print-default-config > my.conf
>gitit -f my.conf
>
>   And even if I didn't change the my.conf at all, it will still gives the
>   error message:
>
>     Could not read mime types file: /etc/mime.types
>     /etc/mime.types: openFile: does not exist (No such file or
>     directory)
>     Using defaults instead.

That's just a warning.  If you don't have /etc/mime.types,
gitit will use its own hard-coded defaults.  This is no
cause for concern.
