### ISSUE TITLE
Poor handling of encoding in file names (unicode support)

### ISSUE THREAD

**Issue by pfctdayelise** [jgm/gitit#378]
http://gitit.net/_categories currently gives:
Server error: /home/website/gitit/wikidata/CrÃ©Ã©e.page: openFile: invalid argument (invalid character)

_index reveals a page with the name Créée. Visiting it ( http://gitit.johnmacfarlane.net/Cr%C3%A9%C3%A9e ) gives
Server error: git: recoverEncode: invalid argument (invalid character)

As do the pages with names in Japanese and Chinese characters.

Possibly the same/related to https://github.com/jgm/gitit/issues/296

**Comment by Cysioland** [comment]
@jgm I still have this problem, I can't see category list, because of

`Server error: wikidata/Gitit User’s Guide.page: openFile: invalid argument (invalid character)`

**Comment by jgm** [comment]
What does `locale` tell you?  Most likely you aren't set up
with a UTF-8 locale.

+++ Cysioland [Sep 11 15 08:17 ]:
