### ISSUE TITLE
More mobile-friendly?

### ISSUE THREAD

**Issue by cnphil** [jgm/gitit#450]
Gitit is absolutely amazing and I use it everyday as my personal knowledge base. I read my wiki on my laptops and my smartphones. The thing is that gitit only has a desktop version so it looks so tiny and hard-to-navigate on smartphones or even tablets. I'm just wondering if there is any plan to make gitit more mobile-friendly, just like what Wikipedia is doing to their mobile versions.

Thanks!

**Comment by lmullen** [comment]
I'm late to this issue, but I found that you can make Gitit's theme responsive with a few lines of CSS, without needing Bootstrap. This page on my [wiki explains how](http://notebook.lincolnmullen.com/Wiki%20hacks#responsive-gitit-theme).

**Comment by jgm** [comment]
Want to submit a PR?

+++ Lincoln Mullen [Oct 07 15 08:12 ]:

**Comment by wcaleb** [comment]
Yes, please! This works great!
