### ISSUE TITLE
MathML exporter is broken

### ISSUE THREAD

**Issue by r-gaia-cs** [jgm/gitit#479]
## Summary

When using MathML option, the LaTeX expression is embed inside `<math>` without the properly tags.

![bug](https://cloud.githubusercontent.com/assets/1506457/5599714/39e2acec-92b3-11e4-9d43-e78f32cfa374.jpg)

## Steps To Reproduce

1. Create `config` with

   ~~~
   math: MathML
   ~~~
2. Create a new wiki

   ~~~
   $ gitit -f config
   ~~~
3. Add `$x$` to some page.
4. Preview the page.

## Actual Results

~~~
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><mi>x</mi>x</math>
~~~

## Expected Results

~~~
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><mi>x</mi></math>
~~~

or

~~~
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>x</mi><annotation encoding="application/x-tex">x</annotation></semantics></math>
~~~

This last one is the output that I got with Pandoc 1.13.2.

## Environment Information

~~~
$ gitit --version
gitit version 0.10.6.1 +plugins
~~~

**Comment by jgm** [comment]
>Actual Results
>
><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><mi>x</mi>x</math>
>
>Expected Results
>
><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><mi>x</mi></math>

What version of texmath did you compile gitit against?

**Comment by r-gaia-cs** [comment]
> What version of texmath did you compile gitit against?
                                                      
I just `sudo cabal install --global` after cloning this Git repository. What command should I use to get texmath's version?

**Comment by jgm** [comment]
ghc-pkg list texmath

+++ Raniere Silva [Jan 03 15 04:15 ]:

**Comment by r-gaia-cs** [comment]
~~~
$ ghc-pkg list texmath            
   texmath-0.6.6.3
   texmath-0.8
   texmath-0.8.0.1
~~~

**Comment by r-gaia-cs** [comment]
After think a little I discovery that this issue is due [xss-sanitize](https://github.com/yesodweb/haskell-xss-sanitize). When I replace

~~~
xss-sanitize: yes
~~~

with

~~~
xss-sanitize: no
~~~

the problem was solved.

@jgm Thanks very much for you time. I'm closing this issue and will report it for xss-sanitize developers.
