### ISSUE TITLE
Edit without a description silently fails

### ISSUE THREAD

**Issue by briandfoy** [jgm/gitit#482]
The Help pages note that you have to have a description to save an edit, but there's no error message when you do that. Additionally, the edits stay in the textarea. There's no entry in the history and the edits are not saved.

An error message would be good.

I'd like to report the version we're using, but I don't see where that's displayed anywhere for a non-admin user.

**Comment by wcaleb** [comment]
You must be using an old version, because the latest version does display a red error message saying "Description cannot be empty."
