### ISSUE TITLE
Cannot build gitit-0.10.6.1 -fplugins on GHC 7.8.4

### ISSUE THREAD

**Issue by mantkiew** [jgm/gitit#484]
It installs fine without `-fplugins` but with the option, I get

```
next goal: ghc (dependency of gitit-0.10.6.1:+plugins)
rejecting: ghc-7.8.4/installed-6c4... (conflict: JuicyPixels =>
transformers==0.4.2.0/installed-686..., ghc =>
transformers==0.3.0.0/installed-645...)
Backjump limit reached (change with --max-backjumps).
```

I'm on Ubuntu with `ghc-7.8.4` and `cabal=1.22.0.0`.

**Comment by jgm** [comment]
It is building fine on travis with ghc 7.8.4.
https://travis-ci.org/jgm/gitit
Probably you're just in cabal hell because of other packages you've installed.  You might try using a cabal sandbox.
