### ISSUE TITLE
HStringTemplate upgrade

### ISSUE THREAD

**Issue by nomeata** [jgm/gitit#485]
Hi,

gitit is currently incompatible with the Stackage LTS release, due to `HStringTemplate (>=0.6 && <0.8)`. Please consider uploading a fixed version, and please also consider adding gitit to stackage: http://www.stackage.org/authors

Thanks,
Joachim

**Comment by jgm** [comment]
Uploaded 0.10.6.2 to Hackage.  This should fix the issue.

+++ Joachim Breitner [Apr 02 15 03:31 ]:

**Comment by nomeata** [comment]
Thanks. It’s stuck via https://github.com/sof/feed/issues/9 now, but this can still be closed.

**Comment by jgm** [comment]
Great.  And a big thanks for your work on Debian Haskell!

+++ Joachim Breitner [Apr 03 15 08:49 ]:
