### ISSUE TITLE
mathjax-script not pointing to a valid script

### ISSUE THREAD

**Issue by cddesja** [jgm/gitit#486]
Hi,
I am not sure if it is just me or not, but when I ran 

    gitit --print-default-config > my.conf

Edited my.conf so that

    math: mathjax

The math was not rendering correctly.

I needed to change 

    mathjax-script: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

and now it works. Not sure if this should be updated or not. As the default value for mathjax-script pointed to a non-existent script.

**Comment by jgm** [comment]
This is fixed in 4a90c9add49d7e3ebd8db2867b81c793702c6a63.
The latest release 0.10.6.2 has this:

mathjax-script: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

which I think is correct.

+++ Christopher David Desjardins [Apr 15 15 09:41 ]:
