### ISSUE TITLE
path.exists is now called `fs.exists`

### ISSUE THREAD

**Issue by hemingwang0902** [jgm/gitit#491]
I  checked out gitit source code from the repository, and change to the gitit directory, install gitit by command `cabal install`. then, I change work directory to *~/Document/myWiki* and execute command `gitit`, output this message:
```textinfo
path.exists is now called `fs.exists`
```
and does not generate any directory or file under *~/Document/myWiki*.

**Comment by jgm** [comment]
+++ 何明旺 [May 07 15 04:26 ]:
>   I checked out gitit source code from the repository, and change to the
>   gitit directory, install gitit by command cabal install. then, I change
>   work directory to ~/Document/myWiki and execute command gitit, output
>   this message:
>path.exists is now called `fs.exists`

This looks like a node.js message.  Gitit doesn't use node,
so I have no idea where this might be coming from.  Does
`which gitit` point to your cabal bin directory?

**Comment by hemingwang0902** [comment]
Thank you for your answer!
```textinfo
# which gitit
/usr/local/bin/gitit
```
under ~/.cabal/bin directory also has a name for the file gitit, and I execute command `~/.cabal/bin/gitit` can output the right content, output as follows:
```textinfo
# ~/.cabal/bin/gitit
Could not read mime types file: /etc/mime.types
/etc/mime.types: openFile: does not exist (No such file or directory)
Using defaults instead.
Created repository in wikidata
Added Front Page.page to repository
Added Help.page to repository
Added Gitit User?. Guide.page to repository
Created static/css/custom.css
Created static/img/logo.png
Created templates/footer.st
``` 
but under */usr/local/bin/* directory why will be more of a name for *gitit* file it? and it's a NodeJs module. I haven't execute the NodeJs command `npm install gitit` to install gitit.

Dit you know that this is how it goes?

**Comment by jgm** [comment]
It seems to be this:

https://github.com/chrismccord/gitit

which looks like a pretty dead project.  Unfortunate name collision.

**Comment by hemingwang0902** [comment]
well, it's should be like this, with your help, my problem has been solved, thanks again !
