### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by magic890** [jgm/gitit#500]
Hi,

I've downloaded the `gitit-0.10.7.zip`, uncompressed it, and now I'm trying to run `cabal install gitit`.
I'm unable to install it because I get this error:

    [root@MACHINE gitit-0.10.7]# cabal install gitit
    Resolving dependencies...
    Configuring cmark-0.3.4...
    cabal-1.16.0.2: Missing dependency on a foreign library:
    * Missing (or bad) header file: cmark.h
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
    If the header file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.
    Failed to install cmark-0.3.4
    Configuring digest-0.0.1.2...
    cabal-1.16.0.2: Missing dependency on a foreign library:
    * Missing (or bad) header file: zlib.h
    * Missing C library: z
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
    If the header file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.
    Failed to install digest-0.0.1.2
    Configuring hslua-0.3.13...
    Building hslua-0.3.13...
    Preprocessing library hslua-0.3.13...
    cabal-1.16.0.2: The program gcc is required but it could not be found.
    Failed to install hslua-0.3.13
    Configuring lifted-base-0.2.3.6...
    cabal-1.16.0.2: Missing dependency on a foreign library:
    * Missing (or bad) header file: inlinable.h
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
    If the header file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.
    Failed to install lifted-base-0.2.3.6
    Warning: memory.cabal: Unknown fields: extra-doc-files (line 25)
    Fields allowed in this section:
    name, version, cabal-version, build-type, license, license-file,
    copyright, maintainer, build-depends, stability, homepage,
    package-url, bug-reports, synopsis, description, category, author,
    tested-with, data-files, data-dir, extra-source-files,
    extra-tmp-files
    Configuring memory-0.7...
    Building memory-0.7...
    Preprocessing library memory-0.7...
    cabal-1.16.0.2: The program gcc is required but it could not be found.
    Failed to install memory-0.7
    Configuring network-2.6.2.0...
    cabal-1.16.0.2: The program gcc is required but it could not be found.
    Failed to install network-2.6.2.0
    Configuring network-info-0.2.0.6...
    Building network-info-0.2.0.6...
    Preprocessing library network-info-0.2.0.6...
    cabal-1.16.0.2: The program gcc is required but it could not be found.
    Failed to install network-info-0.2.0.6
    Configuring primitive-0.6...
    cabal-1.16.0.2: Missing dependency on a foreign library:
    * Missing (or bad) header file: primitive-memops.h
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
    If the header file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.
    Failed to install primitive-0.6
    Configuring regex-pcre-builtin-0.94.4.8.8.35...
    cabal-1.16.0.2: Missing dependency on a foreign library:
    * Missing (or bad) header file: pcre.h
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
    If the header file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.
    Failed to install regex-pcre-builtin-0.94.4.8.8.35
    Configuring regex-posix-0.95.2...
    Building regex-posix-0.95.2...
    Preprocessing library regex-posix-0.95.2...
    cabal-1.16.0.2: The program gcc is required but it could not be found.
    Failed to install regex-posix-0.95.2
    Configuring unix-compat-0.4.1.4...
    cabal-1.16.0.2: Missing dependency on a foreign library:
    * Missing (or bad) header file: HsUnixCompat.h
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
    If the header file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.
    Failed to install unix-compat-0.4.1.4
    Configuring zlib-0.6.1.1...
    Warning: Unknown extensions: DeriveGeneric
    cabal-1.16.0.2: Missing dependency on a foreign library:
    * Missing (or bad) header file: zlib.h
    * Missing C library: z
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
    If the header file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.
    Failed to install zlib-0.6.1.1
    cabal-1.16.0.2: Error: some packages failed to install:
    ConfigFile-1.1.4 depends on regex-posix-0.95.2 which failed to install.
    HTTP-4000.2.20 depends on network-2.6.2.0 which failed to install.
    JuicyPixels-3.2.5.2 depends on zlib-0.6.1.1 which failed to install.
    MissingH-1.3.0.1 depends on regex-posix-0.95.2 which failed to install.
    aeson-0.7.0.6 depends on primitive-0.6 which failed to install.
    cmark-0.3.4 failed during the configure step. The exception was:
    ExitFailure 1
    conduit-1.2.4.2 depends on lifted-base-0.2.3.6 which failed to install.
    connection-0.2.5 depends on network-2.6.2.0 which failed to install.
    cryptonite-0.5 depends on memory-0.7 which failed to install.
    digest-0.0.1.2 failed during the configure step. The exception was:
    ExitFailure 1
    enclosed-exceptions-1.0.1.1 depends on lifted-base-0.2.3.6 which failed to
    install.
    filemanip-0.3.6.3 depends on unix-compat-0.4.1.4 which failed to install.
    gitit-0.10.7 depends on zlib-0.6.1.1 which failed to install.
    happstack-server-7.4.4 depends on zlib-0.6.1.1 which failed to install.
    highlighting-kate-0.6 depends on regex-pcre-builtin-0.94.4.8.8.35 which failed
    to install.
    hoauth2-0.4.8 depends on zlib-0.6.1.1 which failed to install.
    hslogger-1.2.9 depends on network-2.6.2.0 which failed to install.
    hslua-0.3.13 failed during the building phase. The exception was:
    ExitFailure 1
    http-client-0.4.12 depends on zlib-0.6.1.1 which failed to install.
    http-client-tls-0.2.2 depends on zlib-0.6.1.1 which failed to install.
    http-conduit-2.1.5 depends on zlib-0.6.1.1 which failed to install.
    lifted-base-0.2.3.6 failed during the configure step. The exception was:
    ExitFailure 1
    memory-0.7 failed during the building phase. The exception was:
    ExitFailure 1
    network-2.6.2.0 failed during the configure step. The exception was:
    ExitFailure 1
    network-info-0.2.0.6 failed during the building phase. The exception was:
    ExitFailure 1
    pandoc-1.14.0.4 depends on zlib-0.6.1.1 which failed to install.
    pandoc-types-1.12.4.4 depends on primitive-0.6 which failed to install.
    primitive-0.6 failed during the configure step. The exception was:
    ExitFailure 1
    recaptcha-0.1.0.3 depends on network-2.6.2.0 which failed to install.
    regex-compat-0.95.1 depends on regex-posix-0.95.2 which failed to install.
    regex-pcre-builtin-0.94.4.8.8.35 failed during the configure step. The
    exception was:
    ExitFailure 1
    regex-posix-0.95.2 failed during the building phase. The exception was:
    ExitFailure 1
    resourcet-1.1.5 depends on lifted-base-0.2.3.6 which failed to install.
    sendfile-0.7.9 depends on network-2.6.2.0 which failed to install.
    socks-0.5.4 depends on network-2.6.2.0 which failed to install.
    streaming-commons-0.1.12.1 depends on zlib-0.6.1.1 which failed to install.
    texmath-0.8.2 depends on primitive-0.6 which failed to install.
    tls-1.3.1 depends on network-2.6.2.0 which failed to install.
    unix-compat-0.4.1.4 failed during the configure step. The exception was:
    ExitFailure 1
    uuid-1.3.10 depends on network-info-0.2.0.6 which failed to install.
    vector-0.10.12.3 depends on primitive-0.6 which failed to install.
    x509-1.6.0 depends on memory-0.7 which failed to install.
    x509-store-1.6.0 depends on memory-0.7 which failed to install.
    x509-system-1.6.0 depends on memory-0.7 which failed to install.
    x509-validation-1.6.0 depends on network-2.6.2.0 which failed to install.
    yaml-0.8.11 depends on primitive-0.6 which failed to install.
    zip-archive-0.2.3.7 depends on zlib-0.6.1.1 which failed to install.
    zlib-0.6.1.1 failed during the configure step. The exception was:
    ExitFailure 1
    cabal install: /usr/hs/tools/cabal-1.16.0.2 failure (return code=1)

I'm running it on a `CentOS 6`, with `GHC 7.6.3` and `cabal-1.16.0.2`.

How can I solve this issue?

**Comment by jgm** [comment]
Look at the error messages.  One says:

    cabal-1.16.0.2: The program gcc is required but it could not
    be found.

So, first thing I'd do would be install gcc.  Looks like you
also need some libraries (zlib for example).  You shouldn't
need cmark -- the sources are included in the cmark haskell
package -- so I assume this message has something to do with
the missing gcc.


+++ Matteo Guarnerio [Jun 23 15 07:52 ]:

**Comment by magic890** [comment]
Thanks for pointing it out, my fault.
I also added the explicit dependency on the README and created a [pull request](https://github.com/jgm/gitit/pull/501).

Now I have installed it on CentOS 6, and I can't find `gitit` in the PATH.

I'm running it using `/root/.cabal/bin/gitit` and I'm getting this error:

    Created repository in wikidata
    Added Front Page.page to repository
    Added Help.page to repository
    gitit: git: recoverEncode: invalid argument (invalid character)`

My `locale` is: 

    locale: Cannot set LC_CTYPE to default locale: No such file or directory
    locale: Cannot set LC_ALL to default locale: No such file or directory
    LANG=en_US.UTF-8
    LC_CTYPE=UTF-8
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=

is this ok? According to the README it is UTF8.

**Comment by jgm** [comment]
It does sound like a locale-related problem.  I'm not sure exactly what is wrong -- it should be UTF-8, and that looks right here -- but there are two error messages when you run `locale`, and that points to a problem somewhere (not in gitit itself):

>locale: Cannot set LC_CTYPE to default locale: No such file or directory
>locale: Cannot set LC_ALL to default locale: No such file or directory

**Comment by magic890** [comment]
locale `UTF-8` doesn't seems to exist, try to run `locale -a` for all the available options, they are all prefixed with the country code.

> locale: Cannot set LC_CTYPE to default locale: No such file or directory
> locale: Cannot set LC_ALL to default locale: No such file or directory

The two mentioned warning are due to remote SSH client trying to send its LC settings.

For example, running Mac OS X, I have solved this commenting `SendEnv LANG LC_*` in `/etc/ssh_config` file. 

Now my `locale` output is:

    LANG=es_US.UTF-8
    LC_CTYPE="es_US.UTF-8"
    LC_NUMERIC="es_US.UTF-8"
    LC_TIME="es_US.UTF-8"
    LC_COLLATE="es_US.UTF-8"
    LC_MONETARY="es_US.UTF-8"
    LC_MESSAGES="es_US.UTF-8"
    LC_PAPER="es_US.UTF-8"
    LC_NAME="es_US.UTF-8"
    LC_ADDRESS="es_US.UTF-8"
    LC_TELEPHONE="es_US.UTF-8"
    LC_MEASUREMENT="es_US.UTF-8"
    LC_IDENTIFICATION="es_US.UTF-8"
    LC_ALL=

Now I'm trying to run `/root/.cabal/bin/gitit` in an empty folder and I'm stuck here with this output:

    Created repository in wikidata
    Added Front Page.page to repository
    Added Help.page to repository
    Added Gitit User’s Guide.page to repository
    Created static/css/custom.css
    Created static/img/logo.png
    Created templates/footer.st

Why it is not proceeding?

**Comment by jgm** [comment]
Locale looks fine.  So, what is the problem?  When you run gitit, it will create a basic wiki, then wait.  It won't give you the command prompt again -- it's running a web server. Open a browser and look at http://localhost:5001

**Comment by magic890** [comment]
Ok, it's working. Thank you for your support!

Another way to set up the `locale`, just for the current ssh session: `export LC_ALL=en_US.UTF-8`.
