### ISSUE TITLE
gitit-0.11.1 fails to load cmark on Windows

### ISSUE THREAD

**Issue by mantkiew** [jgm/gitit#504]
`gitit-0.11.1`, `Windows 8.1x64`, `MinGHC7.10.1`, `MSYS2`, `cabal-install-1.22.6.0`

```
gitit.exe: C:\.......\.cabal-sandbox\i386-windows-ghc-7.10.1\cmark-0.4.0.1-7ewOlOSYoXt5MoTBz1z1Sw\HScmark-0.4.0.1-7ewOlOSYoXt5MoTBz1z1Sw.o: unknown symbol `___mingw_vsprintf'
gitit.exe: gitit.exe: unable to load package `cmark-0.4.0.1'
```

I am running gitit with a plugin installed into the same sandbox as gitit itself using a command `cabal exec gitit -- -f gitit.cnf`.

**Comment by jgm** [comment]
I'm sorry, I'm not too knowledgeable about Windows, and
I don't know the details of MinGHC.  Does this help?
http://mingw-users.1079350.n2.nabble.com/missing-symbol-ms-vsnprintf-when-linking-with-cross-compiled-library-td7582798.html
It is a similar error message, and I wonder if you are
experiencing something similar: mismatch between the build
MinGW environment and runtime MinGW environment?

+++ Michał Antkiewicz [Jul 24 15 18:22 ]:

**Comment by jgm** [comment]
If necessary, I can try to make the libcmark code more
portable.  (cmark does compile on Windows and is regularly
tested there, but there might be issues if you compile in
a special environment like MinGHC7.10.1.)

+++ Michał Antkiewicz [Jul 24 15 18:22 ]:

**Comment by mantkiew** [comment]
Let me investigate a bit with the new GHC and/or platform to be out "real soon".

**Comment by jgm** [comment]
I've removed the code that uses _vscprintf from libcmark.
So, the problem should be solved anyway with the next
release.

+++ Michał Antkiewicz [Jul 25 15 13:33 ]:

**Comment by jgm** [comment]
I'm seeing a similar error message in an [attempted build of pandoc on Windows using stack](https://ci.appveyor.com/project/jgm/pandoc/build/1.0.5).  This is with the latest cmark, which doesn't use _vscprintf.

If you run gitit directly, rather than using `cabal exec`, do you still get the problem?  I have a feeling it has something to do with that.

**Comment by mantkiew** [comment]
I confirm I see the same issue when building pandoc-1.15.0.6 with stack:

```
pandoc-1.15.0.6.log

    ghc: unable to load package `cmark-0.4.1'
    ghc: C:\Users\......\AppData\Roaming\stack\snapshots\i386-windows\lts-3.3\7.10.2\lib\i386-windows-ghc-7.10.2\cmark-0.4.1-JBAkJhqtQdDC7teYNJOjXQ\HScmark-0.4.1-JBAkJhqtQdDC7teYNJOjXQ.o: unknown symbol `___mingw_vsprintf'
```
But that's a different symbol then `_vscprintf` that you mentioned in your [comment](https://github.com/jgm/gitit/issues/504#issuecomment-124912548). There's an extra 'c' in the name.

**Comment by jgm** [comment]
Sorry, it was a typo on my part.  It's `__mingw__vsprintf` as in your case.

**Comment by mantkiew** [comment]
This does not seem to be a problem anymore. Using pandoc-1.15.2, everything works. I built using `stack` and [lts-3.14](http://www.stackage.org/lts-3.14).

**Comment by mantkiew** [comment]
This does not seem to be a problem anymore. Using pandoc-1.15.2, everything works. I built using `stack` and [lts-3.14](http://www.stackage.org/lts-3.14).

**Comment by mantkiew** [comment]
This does not seem to be a problem anymore. Using pandoc-1.15.2, everything works. I built using `stack` and [lts-3.14](http://www.stackage.org/lts-3.14).

**Comment by mantkiew** [comment]
This does not seem to be a problem anymore. Using pandoc-1.15.2, everything works. I built using `stack` and [lts-3.14](http://www.stackage.org/lts-3.14).

**Comment by mantkiew** [comment]
This does not seem to be a problem anymore. Using pandoc-1.15.2, everything works. I built using `stack` and [lts-3.14](http://www.stackage.org/lts-3.14).
