### ISSUE TITLE
Library vs. executalbe dependencies wrong

### ISSUE THREAD

**Issue by nomeata** [jgm/gitit#507]
Hi,

the gitit cabal file just made the Debian packaging infrastructure trip over. The reason seems to be that there are certain dependencies (most of them, actually) are only listed as dependencies of the executable, but not of the libraries. For example, `Network/Gitit/Authentication.hs` is actually part of the library, and it uses `Network.Captcha.ReCaptcha`, which is in `recaptcha`, which is only listed in the executable’s build-depends.

Why do you not move all the depends to the library section, and have the executable just build-depend on the `gitit` library?

Greetings,
Joachim

**Comment by jgm** [comment]
Yes, that's clearly the way to go.  This cabal file dates
from before cabal allowed you to have an executable depend
on a library defined in the same cabal file, and I guess I
never got around to updating it.  I'll try to do that soon.

+++ Joachim Breitner [Aug 19 15 08:47 ]:

**Comment by jgm** [comment]
This should be fixed by 0.12, just released. Let me know if not.
