### ISSUE TITLE
Installation using stack fails

### ISSUE THREAD

**Issue by gallafent** [jgm/gitit#508]
I have attempted to install gitit using stack on a system running Ubuntu 14.04 x86_64.
First I installed stack using the instructions at https://github.com/commercialhaskell/stack/wiki/Downloads#ubuntu … this installation works fine.
I then follow the instructions at https://github.com/jgm/gitit/blob/master/README.markdown I am asked to do a “stack setup”. This also works fine, and installs GHC for me.
I then try to install gitit again, but see a message “Invalid flag specification: - Package 'pandoc' not found (specified in stack.yaml)”.
I then installed pandoc via stack, using the instructions at https://github.com/jgm/pandoc/blob/master/INSTALL , which (after adding some swap space!) worked, so I now have pandoc in my path (having added ~/.local/bin to $PATH).
I now try again to install gitit using stack, and I still see the same “Package 'pandoc' not found” message, though, even though pandoc is now in my path, and was installed using stack, when I run “stack install” in my gitit checkout.
What should I do now? How do I allow the gitit build to see my pandoc installation?

**Comment by jgm** [comment]
I just pushed a change that might help.  (Sorry, I'm new
to stack.)  Try pulling and stack install again.
Let me know if it works.

+++ gallafent [Aug 21 15 04:41 ]:

**Comment by gallafent** [comment]
Build goes through fine with your fix! Thank for the rapid and effective response. Always good when removing code makes things work :)
