### ISSUE TITLE
Please add the "or later" option to the GPL

### ISSUE THREAD

**Issue by wolftune** [jgm/gitit#512]
I really would like to consider incorporating and building on this in conjunction with other projects under GPL / AGPL, but the limited version-2-only terms are incompatible with GPLv3 / AGPLv3… I know it may involve checking with all 43 contributors, and it could be a little messy, but please please see about just adding the "or later version" clause, making this GPLv2+ so that it maximizes compatibility and interoperability.

Thank you

**Comment by jgm** [comment]
The "or later" is already included in the license clauses
embedded in the source files.

+++ Aaron Wolf [Sep 03 15 12:51 ]:

**Comment by wolftune** [comment]
Oh, thanks! I see that now. I guess I just thought I'd find that reference in LICENSE or in the README or somewhere at the top level. Thanks so much!
