### ISSUE TITLE
Cannot export to PDF

### ISSUE THREAD

**Issue by Cysioland** [jgm/gitit#514]
Exporting to PDF results in the response: `Server error: ExitFailure 97`

And the log entry: `gitit: Could not find data file templates/default.latex`

**Comment by jgm** [comment]
Try `cabal install pandoc`.  These are pandoc data files.
If you built gitit on another machine, they might not be
present on the machine you're using.  Another approach is
to do `cabal install -fembed_data_files pandoc` and then
`cabal install --reinstall gitit`.  This will bake the
needed data files into the binary.

+++ Cysioland [Sep 11 15 08:24 ]:

**Comment by Cysioland** [comment]
After pandoc was installed, I'm now getting following error:

`! LaTeX Error: File `url.sty' not found.`

**Comment by jgm** [comment]
You're missing some latex dependencies.  If you're on a
debian-based machine, try `apt-get install
texlive-recommended`.

+++ Cysioland [Sep 15 15 04:20 ]:

**Comment by Cysioland** [comment]
Fixed on Ubuntu 14.04 by installing following packages: `texlive-latex-base texlive-latex-extra texlive-fonts-recommended`
