### ISSUE TITLE
Put templates directory in version-control as well?

### ISSUE THREAD

**Issue by matthiasbeyer** [jgm/gitit#517]
Is there an option to include all directories in the version control?

I tried to create a git directory in the root of the gitit project, but it creates another git repository in `wikidata`, so stuff from `templates` doesn't get version controlled.

Any way to get this working? I do not see a point in putting templates into _another_ repository, though!

**Comment by jgm** [comment]
You can specify the path of the templates directory in
the config file (`templates-dir` field).

Just set it to a path inside your repository.


+++ Matthias Beyer [Sep 19 15 14:12 ]:

**Comment by matthiasbeyer** [comment]
Okay, that worked for me. Should I open another issue for more questions?

If not: How to pass something to a template? I created a template for a fenced code block - but I want to be able to pass the actual code to it - how do I do that?

**Comment by wcaleb** [comment]
@matthiasbeyer Some of your questions about Gitit usage might be better answered on the [gitit-discuss](https://groups.google.com/forum/#!forum/gitit-discuss) mailing list. The issues tracker here is usually reserved for reporting bugs.

**Comment by matthiasbeyer** [comment]
ok. sorry.

**Comment by jgm** [comment]
Best place for questions is the gitit-discuss group on
Google Groups. Questions should not go on the bug tracker.

+++ Matthias Beyer [Sep 20 15 10:56 ]:
