### ISSUE TITLE
Integrate alternative editor?

### ISSUE THREAD

**Issue by matthiasbeyer** [jgm/gitit#518]
Hi,

is there a way (if not, this is a feature request) to integrate an alternative editor into gitit?

I think of [stackedit](https://stackedit.io), but there might be others, of course.

---

Edit:

There are some others:

* http://dillinger.io/ - https://github.com/joemccann/dillinger
* http://epiceditor.com/ - https://github.com/OscarGodson/EpicEditor/
* https://jbt.github.io/markdown-editor/ - https://github.com/jbt/markdown-editor

**Comment by wcaleb** [comment]
See instructions from @lmullen on how to use ACE editor:

http://notebook.lincolnmullen.com/Wiki%20hacks#ace-editor-with-syntax-highlighting-and-vim-mode

Sent from my iPhone

W. Caleb McDaniel
Associate Professor of History
Duncan College Master
Rice University

http://wcm1.web.rice.edu/
http://www.duncancollege.net/

**Comment by matthiasbeyer** [comment]
Got ACE working.

For future reference:

* one cannot include stackedit as editor in pages, sadly.
* Dillinger should work (I didn't try, though)
* epiceditor should work (I didn't try, though)
* "markdown-editor" seems like a not that professional project like the others, so I didn't try it.

I will close this now, as I'm satisfied with ACE by now. Maybe I will come back later for a Markdown editor.
