### ISSUE TITLE
After installation on Debian w/ Haskell Platform: no feed and no commits either?

### ISSUE THREAD

**Issue by MatthiasKauer** [jgm/gitit#520]
Hi,
I just went through the installation with the Haskell platform.
After
```
cabal update
cabal install gitit
```
as described, gitit was not in the PATH, but I could start it using
```
~/.cabal/bin/gitit
```
In this way, it created the files, but it doesn't seem to commit them. ```git log``` shows nothing.
I tried this in two folders with and without ```git init```. Can I debug this issue somehow or is that normal?

I'm also wondering about the feed that I saw on the demo site. Do I have to activate it somehow? It doesn't appear here.

Last thing:
```
matthias@firedeb:~/dvl/gitit2$ ~/.cabal/bin/gitit --version
gitit version 0.12.0.1 -plugins
```

I suppose -plugins is bad? How do I go about fixing that?

Sorry for so many questions at once, I realize I'm somewhat late to the party here, but I'm quite excited to have found this project :)

**Comment by jgm** [comment]
+++ MatthiasKauer [Nov 09 15 06:23 ]:
>   Hi,
>   I just went through the installation with the Haskell platform.
>   After
>cabal update
>cabal install gitit
>
>   as described, gitit was not in the PATH, but I could start it using
>~/.cabal/bin/gitit
>
>   In this way, it created the files, but it doesn't seem to commit them.
>   git log shows nothing.

They would be in the wikidata folder, which should be a
separate repository.  cd wikidata and try git log there.

>   I tried this in two folders with and without git init. Can I debug this
>   issue somehow or is that normal?
>
>   I'm also wondering about the feed that I saw on the demo site. Do I
>   have to activate it somehow? It doesn't appear here.

You need to turn this on in a custom config file. See the
commented config file in the data/ directory, and when
you've written a config file, use the -f command line option.

>
>   Last thing:
>matthias@firedeb:~/dvl/gitit2$ ~/.cabal/bin/gitit --version
>gitit version 0.12.0.1 -plugins
>
>   I suppose -plugins is bad? How do I go about fixing that?

Compile with the plugins flag (see the README).  If you use
cabal, add `-fplugins` to your `cabal install` command line.

**Comment by MatthiasKauer** [comment]
This was all spot on and I got things going now.
Thank you so much!
