### ISSUE TITLE
How to edit a page with local editors? for example, sublime text 2.

### ISSUE THREAD

**Issue by Edenharder** [jgm/gitit#522]
I really love gitit. But I find that:
1. The changes I make with local editors will not be stored.
2. A page copied from other wiki will not appear online.
How to solve these questions?

**Comment by jgm** [comment]
+++ Edenharder [Dec 06 15 06:36 ]:
>   I really love gitit. But I find that:
>   1. The changes I make with local editors will not be stored.

If you're editing a file in a local copy of your wikidata
repository, then you'll need to use git to commit the change
(and push, if it's a copy of the repository) before it will
show up in gitit.

>   2. A page copied from other wiki will not appear online.

I don't understand.  More detail?

**Comment by Edenharder** [comment]
Thanks very much! I understand. Please close this issue.

**Comment by jgm** [comment]
If you opened it, you should be able to close it yourself.

+++ Edenharder [Dec 06 15 17:38 ]:
