### ISSUE TITLE
Feature Request: See diffs of revisions.

### ISSUE THREAD

**Issue by benpro** [jgm/gitit#530]
Hello,

It would be nice to displays the differences between revisions.

My 2 cts,

**Comment by jgm** [comment]
You can already do that.  Go to history and drag one
revision onto another, and you'll get a diff.

EXample:
http://gitit.net/_diff/Front%20Page?from=65542d48af6c30580e754d7c345823fad55e2730&to=d9c3fecd80e032869beb8480b6abde1606710055

+++ Benoît.S [Dec 27 15 10:56 ]:

**Comment by benpro** [comment]
Wow, my bad! Didn't see the message ```Drag one revision onto another to see differences.```

Sorry!
