### ISSUE TITLE
lines with math are too tall

### ISSUE THREAD

**Issue by kevinclancy** [jgm/gitit#537]
Wiki pages containing latex math looked great in firefox, up until a few ago, at which point lines with math in them were given way too much vertical space. Some piece of external software that gitit depends upon must have changed. I am running Ubuntu 14, and have reproduced the same problem with Firefox 44, 43.04, and 41. I have also reproduced the problem using a freshly generated gitit wiki.

![gitit_tragedy](https://cloud.githubusercontent.com/assets/1915968/12596827/e6fa5712-c44f-11e5-8c17-b51daa1f75c0.png)

**Comment by jgm** [comment]
What method are you using to display math?  Default is
mathjax (at least in recent versions), but this can be
changed using a config file.

Did you recently upgrade gitit?  firefox?

If neither, then most likely something changed with the
external MathJax javascript.  You might enquire over at
MathJax.

+++ Kevin Clancy [Jan 26 16 14:12 ]:

**Comment by kevinclancy** [comment]
I am using mathjax to display math. I believe that Firefox recently auto-updated; however, after trying several versions of Firefox, I am not sure that Firefox is the problem. Gitit has not been updated since I used it last fall.

**Comment by kevinclancy** [comment]
I was able to solve this problem by reinstalling gitit using Stack.
