### ISSUE TITLE
http://gitit.net/_categories returns "invalid character"

### ISSUE THREAD

**Issue by colcord** [jgm/gitit#538]
click on

http://gitit.net/_categories

see following text

start quote

Happstack 7.3.9

Something went wrong here
Internal server error
Everything has stopped

The error was "/home/website/gitit/wikidata/Créée.page: openFile: invalid argument (invalid character)"

end quote

looks very similar to: https://github.com/jgm/gitit/issues/378 (but that issue is closed)
slightly similar to: Crash on non ascii discription of changes #393

**Comment by jgm** [comment]
I think I've fixed this now, by setting the LANG environment
variable in the apache process to en_US.UTF-8.

+++ colcord [Jan 27 16 07:11 ]:

**Comment by colcord** [comment]
Hi John, yes, that works now for me. Thanks for fixing it so quickly. I
look forward to installing gitit on my ubuntu machine. kind regards, Frank

On 27 January 2016 at 17:19, John MacFarlane <notifications@github.com>
wrote:

> I think I've fixed this now, by setting the LANG environment
> variable in the apache process to en_US.UTF-8.
>
> +++ colcord [Jan 27 16 07:11 ]:
> > click on
> >
> > http://gititnet/_categories
> >
> > see following text
> >
> > start quote
> >
> > Happstack 739
> >
> > Something went wrong here
> > Internal server error
> > Everything has stopped
> >
> > The error was "/home/website/gitit/wikidata/Crééepage: openFile:
> > invalid argument (invalid character)"
> >
> > end quote
> >
> > looks very similar to: https://githubcom/jgm/gitit/issues/378 (but that
> > issue is closed)
> > slightly similar to: Crash on non ascii discription of changes [1]#393
> >
> > —
> > Reply to this email directly or [2]view it on GitHub.
> >
> >References
> >
> > 1. https://github.com/jgm/gitit/issues/393
> > 2. https://github.com/jgm/gitit/issues/538
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgm/gitit/issues/538#issuecomment-175754136>.
>



-- 
frank@colcord.net, cell: +447763116793, skype: colcord,
if you ever get no response, please send to: fcolcord@gmail.com
