### ISSUE TITLE
Please consider joining stackage

### ISSUE THREAD

**Issue by nomeata** [jgm/gitit#540]
Hi John,

In Debian, we’d like to upgrade pandoc to 0.16, but it turns out that this is blocked on gitit depending on `<1.16`. Besides upgrading gitit to allow the latest pandoc, would you consider adding gitit to stackage so that such problems are found earlier and centrally?

Greetings,
Joachim

**Comment by jgm** [comment]
Joachim,

I just released 0.12.1, which should work with latest pandoc.

I don't want to add to stackage -- I barely maintain gitit.
I have too many other projects, and I don't use gitit
myself. I've tried several times to find a reliable person
to take over as maintainer.  So I don't want to take on the
commitments that stackage entails.

Best,
John

+++ Joachim Breitner [Feb 17 16 06:39 ]:

**Comment by sjakobi** [comment]
I'd also love to see gitit on stackage!
