### ISSUE TITLE
Demo sandbox has a link to an image that doesn't exist

### ISSUE THREAD

**Issue by reagle** [jgm/gitit#543]
Minor issue: `http://gitit.net/_edit/Sandbox` has example `![image](/img/gitit-banner.png)` which doesn't work upon paste.

**Comment by jgm** [comment]
I'm confused.  There's currently no Sandbox page on
gitit.net.

+++ Joseph Reagle [Mar 26 16 09:13 ]:

**Comment by reagle** [comment]
![gitit](https://cloud.githubusercontent.com/assets/596814/14228129/77c5ad82-f8da-11e5-90ea-f42fba14294f.png)

**Comment by reagle** [comment]
I'm speaking about the example markdown on the left. The natural thing to try is to paste that into the sandbox and preview, but the one image link won't work.
