### ISSUE TITLE
Categories page is empty

### ISSUE THREAD

**Issue by ickc** [jgm/gitit#547]
In my <http://0.0.0.0:5001/_categories>, it is empty, although in the individual files, categories are added as comma separated, e.g. like this `categories: Physics, Optics, PHYS7C`.

And on the bottom of the page, it can show the categories `Physics Optics PHYS7C` with links to <http://0.0.0.0:5001/_category/Physics>, etc.

I used both folder structure and categories to organize my stuffs. I'm not sure where is the source of the problem I'm experiencing. By the way, the YAML are ended in `---` rather than `...` which seems to be not the problem. I also tried space separated rather than comma separated, with no luck. By the way, I used `md` as my file extension instead of `page`, not sure if it would be the problem.

Do you have any idea on how to make it work?

**Comment by jgm** [comment]
Could you put up a little git repository that I could clone
to reproduce the problem?

**Comment by ickc** [comment]
After doing some test, I found out the condition that categories will disappeared: when the YAML front matter ends with `---` instead of `...`. (I made a mistake when I said I tested this, I thought I have, but either there's some other problem or I wasn't paying attention).

The interesting thing is, even if the YAML front matter ends with `---`, the categories page (<http://0.0.0.0:5001/_categories>) will then be empty, but at the end of the page those categories are there.

If you need, I opened a testing repository in [ickc/gitit-test-categories](https://github.com/ickc/gitit-test-categories). The instance that categories has broken is when I did the last commit: `Changed yaml ending to `---``. You can see from these 2 pages:

1. <http://0.0.0.0:5001/_categories>
2. <http://0.0.0.0:5001/test-categories>

The former has nothing, the later has categories in the end.

[I attached my conf here](https://github.com/jgm/gitit/files/229038/default.conf.zip), where the only thing changed is the location of the wikidata.

**Comment by ickc** [comment]
> Could you put up a little git repository that I could clone
> to reproduce the problem?

Are you able to reproduce the problem? Thanks.

**Comment by jgm** [comment]
The metadata in grit must end with `...`; `---` is not allowed.
So that is the problem here...I'm not sure why it partially works when you do the wrong thing.

**Comment by jgm** [comment]
Can you build the latest from HEAD and test this?

**Comment by ickc** [comment]
> Can you build the latest from HEAD and test this?

I tested and verified that the bug is fixed. I will then removed the test repository above. Thanks again!
