### ISSUE TITLE
GitHub login failing

### ISSUE THREAD

**Issue by jluttine** [jgm/gitit#553]
I'm not able to login to gitit.net using GitHub authentication. I get the following error page:
```
Happstack 7.3.9

Something went wrong here
Internal server error
Everything has stopped

The error was ": openFile: does not exist (No such file or directory)"
```

**Comment by jgm** [comment]
Problem was an empty 'gitit-users' field in config.
Will fix.

+++ Jaakko Luttinen [Jun 01 16 00:36 ]:
