### ISSUE TITLE
umlauts in page titles

### ISSUE THREAD

**Issue by brefan** [jgm/gitit#560]
After creating a page with an umlaut in the title, i noticed the following:
* In Recent activity umlauts like ä appear as � in the link in the last bracket. clicking the link produces:  
The error was "git: recoverEncode: invalid argument (invalid character)"
* In All pages, the page appears with the � in the title, clicking it produces:  
The error was "git: recoverEncode: invalid argument (invalid character)"
* Clicking Categories produces:  
The error was "wikidata/page title with �: openFile: invalid argument (invalid character)"

**Comment by jgm** [comment]
Check that your locale is UTF-8.


+++ brefan [Jul 04 16 03:55 ]:

**Comment by jgm** [comment]
Seems to work fine in the demo
http://gitit.net/%C3%A4

+++ brefan [Jul 04 16 03:55 ]:

**Comment by brefan** [comment]
Setting the locale to utf-8 works. Thank you.

**Comment by fkohrt** [comment]
For the record: using a docker container, setting the environment variable `LC_ALL=C.UTF-8` did the trick for me.
