### ISSUE TITLE
Can not `git push origin master` automaticly

### ISSUE THREAD

**Issue by YanhaoMo** [jgm/gitit#562]
Here is the errors:
```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Maybe it is because the user who execute this command on server side is `www-data` (I am not sure)rather than `root`.
I only configure root user but do nothing for other users, and the root can execute the command correctly.

**Comment by jgm** [comment]
This isn't a gitit issue.  It's up to you to
configure your git repository so the people
who need access can get it.  It is definitely
possible to get this working with gitit.

+++ Yanhao Mo [Jul 27 16 19:05 ]:

**Comment by YanhaoMo** [comment]
oops，my mistake， I forgot that I run my wiki in a docker container, and I didn't configure it.
