### ISSUE TITLE
Dot plugin compilation fails with ghc-7.10.3

### ISSUE THREAD

**Issue by Oblynx** [jgm/gitit#568]
Upon attempting to start gitit the following error message is produced:

```
Loading plugin 'plugins/Dot.hs'...

plugins/Dot.hs:38:28:
    Couldn't match expected type ‘Inline’
                with actual type ‘Target -> Inline’
    Probable cause: ‘Image’ is applied to too few arguments
    In the expression: Image name ("/img" </> outfile, "")
    In the first argument of ‘Para’, namely
      ‘[Image name ("/img" </> outfile, "")]’

plugins/Dot.hs:38:34:
    Couldn't match type ‘[Inline]’
                   with ‘(String, [String], [(String, String)])’
    Expected type: Attr
      Actual type: [Inline]
    In the first argument of ‘Image’, namely ‘name’
    In the expression: Image name ("/img" </> outfile, "")

plugins/Dot.hs:38:39:
    Couldn't match expected type ‘[Inline]’
                with actual type ‘(FilePath, [Char])’
    In the second argument of ‘Image’, namely
      ‘("/img" </> outfile, "")’
    In the expression: Image name ("/img" </> outfile, "")
    In the first argument of ‘Para’, namely
      ‘[Image name ("/img" </> outfile, "")]’
gitit: Error loading plugin: plugins/Dot.hs
```

System config:
- ubuntu xenial server
- ghc version= 7.10.3
- cabal-install version= 1.22.6.0
- cabal library version= 1.22.5.0
- gitit version: 0.12.1.1 -plugins

(the latest packages available in the official ubuntu repositories)

**Comment by Oblynx** [comment]
Has anyone else encountered this issue?

**Comment by icefoxen** [comment]
Yyyyep.  ghc version 8.0.1.  Not sure what to do about it though.

**Comment by Oblynx** [comment]
@icefoxen Do you use stack to install and run gitit? I'm having trouble starting the Dot plugin and it looks like it doesn't find the correct libraries, because I have a system ghc version and stack installed. Have you had a similar issue?

Thanks for the fix!

**Comment by icefoxen** [comment]
@Oblynx Yes, I use stack to build and run it.  Both my system ghc and stack come from my package manager; I'm using Debian Stretch.
