### ISSUE TITLE
git repository is not created

### ISSUE THREAD

**Issue by andrewufrank** [jgm/gitit#569]
i intended a configuration, where the wiki pages are in a directory wiki and the my.conf configuration file is in the same directory. in my.conf the entry for where the wikipages are is 
    /home/xx/wiki
This configuration confuses gitit when starting (if constructed later, it is works); some pages are constructed but the git repository is not created. 
it seems that in the directory where the my.conf file resides, other files are constructed, including the directory wikidata. to achieve this, the entry in my.conf must be 
    /home/xx/wiki/wikidata
with my.conf in wiki.
i do not think this is an error in the program, but warrants an explanation, perhaps with a recommendation to put my.conf in a directory wikistuff and put in my.conf 
/home/..../wikistuff/wikidata
or drop the need for wikidata and require in my.conf only the path to the directory in which wikidata will be creadte (problem: breaks current my.conf).
thank you for a great program which works nicely!

**Comment by jgm** [comment]
+++ andrew u frank [Sep 25 16 10:54 ]:
>   i intended a configuration, where the wiki pages are in a directory
>   wiki and the my.conf configuration file is in the same directory. in
>   my.conf the entry for where the wikipages are is
>   /home/xx/wiki
>   This configuration confuses gitit when starting (if constructed later,
>   it is works); some pages are constructed but the git repository is not
>   created.

That's because gitit will only create a repository if the
directory specified doesn't already exist.

**Comment by andrewufrank** [comment]
i have corrected the configuration. perhaps some rephrasing the instruction may be possible.

 - thank you for the clarification
