### ISSUE TITLE
gitit with systemd

### ISSUE THREAD

**Issue by andrewufrank** [jgm/gitit#570]
i have created a bash file and a systemd gitit.service file:

the bash  giti_start.sh  (which i put into /etc/systemd/system - probably there are more appropriate locatios!)  

```
#!/bin/sh
exec /home/xx/.cabal/bin/gitit -f /home/user1/Data/wiki/my.conf  &
exec /home/xx/.cabal/bin/gitit -f /home/user2/wiki/my.conf  &
exec /home/x/.cabal/bin/gitit -f /home/user3/wiki/my.conf  &
```

and the service file gitit.service (goes to /etc/systemd/system)

```
[Unit]
Description=start gitit wiki    

[Service]
Type=forking
ExecStart=/etc/systemd/system/gitit_start.sh

[Install]
WantedBy=multi-user.target
```

start with systemctl start gitit

this is one of my first attempts with systemd - perhaps somebody can suggest a better solution?

**Comment by norpol** [comment]
I guess an appropriate location for your shell script would be `/usr/local/bin/` [[1]](http://www.comptechdoc.org/os/linux/usersguide/linux_ugfilestruct.html).
It is discouraged to run the gitit as a root user, you should use either an own gitit user for every different gitit instance you have running, or at least have the gitit user running with the same user as the files are created. Also you need to make sure the path and files are accessible from this user.
We can maybe help you better if you describe us what you are trying to accomplish. :smile:

**Comment by andrewufrank** [comment]
i will change the configuration as you suggest and introduce a gitit user and move the shell script. 
i have several wikis (for different family members) with low security requirements, therefore i think that a single gitituser will be sufficient. 
is the systemd service file ok?
thank you for the advice and help!
