### ISSUE TITLE
can not replace logo

### ISSUE THREAD

**Issue by andrewufrank** [jgm/gitit#571]
i have tried to replace the logo.png file in static/img but i always get the (mirrored lambda) dog back. 
i see always a directory /static..  in the root of the file system (recreated whenever gitit starts). this directory contains the dog image, independent of what is in the directory in the user's wiki.

i have gitit 0.12.1.1  compiled with ghc 8.0.1 on armhf.

otherwise: a super wiki! thank you

**Comment by jgm** [comment]
Yes, static/ is independent of the wiki.
Just modify the logo file there (not in your wikidata
directory).

+++ andrew u frank [Sep 28 16 03:00 ]:

**Comment by andrewufrank** [comment]
this means, i have only one logo for all wikis on the same computer? 
where is /static comming from (i.e. where is the file i have to change?)

is there a way that each wiki has its own logo (i.e. the one which is stored in its static folde) ? if i have more than one wiki on the same computer and it would be desirable to have three different logo files to separate the wiki and avoid mistakes. 
thank you for help!

**Comment by jgm** [comment]
You can have a different static directory for each
wiki.  There's a field for this in the config file.
See the commented up config file.

+++ andrew u frank [Sep 28 16 14:40 ]:

**Comment by andrewufrank** [comment]
thank you - i did not realize `static-dir: static`  could be required to be set. 
this fixes my problem (perhaps you edit the instructions, they did confuse me at least).
