### ISSUE TITLE
Could not find module Network.URI

### ISSUE THREAD

**Issue by Alok** [jgm/gitit#576]
```
Could not read mime types file: /etc/mime.types
/etc/mime.types: openFile: does not exist (No such file or directory)
Using defaults instead.
Loading plugin 'plugins/Interwiki.hs'...
gitit: Could not find module ‘Network.Gitit.Interface’
Use -v to see a list of the files searched for.
Could not find module ‘Network.URI’
Use -v to see a list of the files searched for.
```

I do have those modules installed, but `gitit` can't seem to find them.

**Comment by jgm** [comment]
+++ Alok Singh [Oct 07 16 15:33 ]:
>Could not read mime types file: /etc/mime.types
>/etc/mime.types: openFile: does not exist (No such file or directory)
>Using defaults instead.
>Loading plugin 'plugins/Interwiki.hs'...
>gitit: Could not find module ‘Network.Gitit.Interface’
>Use -v to see a list of the files searched for.
>Could not find module ‘Network.URI’
>Use -v to see a list of the files searched for.
>
>   I do have those modules installed, but gitit can't seem to find them.

Perhaps you installed them with stack, which doesn't put
them in the default place?

**Comment by Alok** [comment]
I installed them with stack, and then with cabal. I now get the following error:

```haskell
plugins/Interwiki.hs:37:24:
    Constructor ‘Link’ should have 3 arguments, but has been given 2
    In the pattern: Link ref (interwiki, article)
    In an equation for ‘convertInterwikiLinks’:
        convertInterwikiLinks (Link ref (interwiki, article))
          = case interwiki of {
              ('!' : interwiki')
                -> case M.lookup interwiki' interwikiMap of {
                     Just url -> ...
                     Nothing -> Link ref ... }
                where
                    interwikiurl a u = escapeURIString isAllowedInURI $ u ++ a
                    summary a = interwiki' ++ ": " ++ a
              _ -> Link ref (interwiki, article) }
gitit: Error loading plugin: plugins/Interwiki.hs
```

**Comment by marcelhuberfoo** [comment]
I had the same issue, unfortunately the dependency management for building gitit seems to be hard to manage and I wonder if there could be an explanatory page providing a always working step-by-step building cookbook. 'Always working' should include tagged versions.

**Comment by jgm** [comment]
There were some changes to pandoc-types internals in recent
pandoc versions, so if you compile gitit with recent pandoc,
you'll need some changes in the plugins too.

If someone wants to update these plugins for latest pandoc,
I'd accept a PR.

+++ Alok Singh [Oct 16 16 16:31 ]:

**Comment by marcelhuberfoo** [comment]
@jgm Would it be possible to extend the code to be interface compatible with both versions using an ifdef like construct testing for the pandoc-types version?

**Comment by jgm** [comment]
Perhaps.  You can use CPP in Haskell source files, but the
plugin interface would have to explicitly enable the
CPP extension.  I'm not positive it would work.

+++ Marcel Huber [Oct 17 16 00:32 ]:
