### ISSUE TITLE
gitit in github/gitlab pages

### ISSUE THREAD

**Issue by csantosb** [jgm/gitit#577]
Hi, first thanks for gitit, this really helps to organize data.

I was just wondering if it would be possible to host gitit online as
github/gitlab pages. This would greatly help to document projects,
effectively replacing default wiki.

Thanks !

**Comment by jgm** [comment]
+++ Cayetano Santos [Oct 15 16 03:28 ]:
>   Hi, first thanks for gitit, this really helps to organize data.
>
>   I was just wondering if it would be possible to host gitit online as
>   github/gitlab pages. This would greatly help to document projects,
>   effectively replacing default wiki.
>

No, not really -- gitit is a dynamic wiki and requires its
own server.  GitHub pages serves static HTML.

**Comment by csantosb** [comment]
Yeah, this is what I supposed, but just in case. Thanks.
