### ISSUE TITLE
Feature request(s): create new page button, create new page from search

### ISSUE THREAD

**Issue by Alok** [jgm/gitit#578]
I'm not sure if this can be done via plugins instead.

Essentially, the option to have a "create new page" button. There may be something about the concept of wikis that I'm missing, but requiring users to link their page to existing ones is sometimes rather annoying, especially if you like to do all your inter-page linking at a later date.

Wikipedia has the second feature. If you search for a page that doesn't exist, it offers to create it.

**Comment by jgm** [comment]
You can just navigate to

    http://localhost:5001/MyPageName

and it will offer to create it (assuming your wiki is hosted
at http://localhost:5001).

+++ Alok Singh [Oct 16 16 16:39 ]:

**Comment by Alok** [comment]
I'm aware. It's more that I'm curious why wikis don't let you just
explicitly create a page. Going to a currently nonexistent URL seems like
rather a lot of indirection.

-- Alok

**Comment by jgm** [comment]
+++ Alok Singh [Oct 17 16 00:51 ]:
>   I'm aware. It's more that I'm curious why wikis don't let you just
>   explicitly create a page. Going to a currently nonexistent URL seems
>   like
>   rather a lot of indirection.

I don't know.  It may be that the idea was to make sure that
new pages are linked somewhere.
