### ISSUE TITLE
Links: "Display" name vs "path" name

### ISSUE THREAD

**Issue by Alok** [jgm/gitit#601]
> In Wikipedia's markup language, you create free links by putting double square brackets around text designating the title of the page you want to link to. Thus, `[[Texas]]` will be rendered as Texas. Optionally, you can use a vertical bar (`|`) to customize the link title. For example, typing `[[Texas|Lone Star State]]` will produce Lone Star State, a link that is displayed as "Lone Star State" but in fact links to Texas.

I was wondering if gitit has a similar feature, and if not, if such a thing could be added, (perhaps as a plugin?). Sometimes it's awkward writing to write the literal link name for some wiki pages.

**Comment by jgm** [comment]
In gitit this is done just slightly differently:

    [[Texas]] --> [Texas]()
    [[Texas|Lone Star State]] -> [Lone Star State](Texas)


+++ Alok Singh [Mar 27 17 23:27 ]:
