### ISSUE TITLE
Dependency conflicts on GHC 8.6

### ISSUE THREAD

**Issue by Rufflewind** [jgm/gitit#625]
The recent release of GHC 8.6 has broken Gitit again:

* gitit-0.12.3 depends on the outdated hoauth2-1.7, which depends on the outdated exceptions-0.8.3, which depends on the outdated template-haskell-2.13 (Fix: bump gitit's cabal to use hoauth2-1.8)
* https://github.com/Happstack/happstack-server/issues/48 happstack-server-7.5.1.1 (latest) depends on the outdated template-haskell-2.13 (Fix: bump happstack-server's cabal to use template-haskell-2.14)
* uri-0.1.6.5 (latest) requires an outdated parsec >=3.0 && <=3.1.11, but pandoc-2.4 (latest) requires haddock-library-1.7.0, which requires a newer parsec >=3.1.13.0 && <3.2 (Fix: ???)

I gave up trying so there might be more issues beyond these three.

**Comment by jgm** [comment]
PRs welcome!

For the `uri` issue, one probably needs to nudge the maintainer, or find another library that does what we need from `uri`.

**Comment by Rufflewind** [comment]
When should I expect a release with these fixes?

**Comment by jgm** [comment]
Is there a release of happstack-server that fixes the issue there?

**Comment by Rufflewind** [comment]
Yep! 7.5.1.2
