### ISSUE TITLE
Is gitit.net still valid?

### ISSUE THREAD

**Issue by Rufflewind** [jgm/gitit#627]
It now points to:

> GITIT
> GROUP IN LOGIC AND THE METHODOLOGY OF SCIENCE

which doesn't look like a gitit wiki anymore?

**Comment by jgm** [comment]
That's extremely bizarre.  I gave up paying for the
domain name, so I assume someone else has it and
has created this content (which oddly has some
relation to me).

I'm not sure what the person who owns it is trying to
accomplish here.

**Comment by Rufflewind** [comment]
The URL is still in the .cabal file BTW.

**Comment by jgm** [comment]
Oh, thanks, I'll correct that.
