### ISSUE TITLE
Text won't get italicized

### ISSUE THREAD

**Issue by fkohrt** [jgm/gitit#650]
I have no clue to the why, but the following [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) wiki site won't show the text behind the second link italicized.

```
- [TiddlyWiki](https://tiddlywiki.com/) _non-linear web notebook_
  - [Dropboard](https://github.com/reidgould/tiddlywiki-dropboard) _this won't get italicized_
```

Instead, it shows the underscores:
![screenshot](https://user-images.githubusercontent.com/12914806/76688329-0a8f9e80-662c-11ea-9b03-c14f04b37315.png)

**Comment by jgm** [comment]
I can't reproduce this.  I see the italics.

**Comment by fkohrt** [comment]
Strange. Although unlikely, I had hoped that this reproduces. I guess it must somehow be my environment... Closing this issue.
