### ISSUE TITLE
version on hackage doesn't build with filestore>=0.6.3.5

### ISSUE THREAD

**Issue by hsenag** [jgm/gitit#656]
I got build failures with gitit 0.12.3.2 from hackage and had to dig around for a while to find the problem with the Diff/PolyDiff migration, and then #637 documenting it (particularly as it's closed). 

Could you consider making a new release of gitit, and/or using hackage revisions to put an upper bound on filestore (<0.6.3.5) on the existing versions?

The hackage failure is also visible here: https://matrix.hackage.haskell.org/#/package/gitit/0.12.3.2/ghc-8.6.5@1586535005

**Comment by jgm** [comment]
I just released a new version.
