### ISSUE TITLE
<summary> tag in markdown preserved by pandoc, but removed in gitit

### ISSUE THREAD

**Issue by zoickx** [jgm/gitit#661]
Consider the following piece of markdown displayed through gitit:

``` markdown
##### I am markdown and below should be a spoiler

<details>
<summary>Summary text.</summary>
<p>Inner paragraph.</p>
</details>
```

### Expected result

When processed with `pandoc 2.10` the same markdown results in (note that `<summary>` tags are present):

``` html
<h5 id="i-am-markdown-and-below-should-be-a-spoiler">I am markdown and below should be a spoiler</h3>
<details>
<summary>
Summary text.
</summary>
<p>
Inner paragraph.
</p>
</details>
```
Which looks like (*this will be correctly displayed on github, but not on gitit*)

##### I am markdown and below should be a spoiler

<details>
<summary>Summary text.</summary>
<p>Inner paragraph.</p>
</details>

### Actual result

On gitit, installed via `stack install` on checkout [`ae4f450`][COMMIT], it is displayed as the following HTML
(note the lack of `<summary>` tags):

``` html
<h5 id="i-am-markdown-and-below-should-be-a-spoiler">I am markdown and below should be a spoiler</h3>
<details open="">

Summary text.

<p>
Inner paragraph.
</p>
</details>
```

[Here is an example.](http://209.250.240.187:5001/Test%20snippet)

[COMMIT]: https://github.com/jgm/gitit/commit/ae4f450cb9a4888c09e64761e8f1bdb58b3e6789

### Further details

There seems to be no way to display a block like

<details>
<summary>Spoiler heading</summary>
Spoiler content
</details>

in gitit right now. "Spoiler heading" becomes part of spoiler text and in its place the word "Details" is put, like so:

<details>
<summary>Details.</summary>
Spoiler heading

Spoiler content
</details>

I have tested this with different versions of `pandoc` and `gitit` + with different browsers, the problem persists regardless. Also put up an example instance at <http://209.250.240.187:5001>

Is gitit supposed to serve html precisely as produced by pandoc? If so, this looks like a bug.

**Comment by jgm** [comment]
Probably it's getting stripped off as raw HTML. You could try setting `xss-sanitize: no` in the config.

**Comment by zoickx** [comment]
Ah, simple as that, how did I miss it... That works, thank you!

To reformulate my question though, should I expect gitit to always serve htmls exactly as produced by pandoc now that `xss-sanitize` is set to `no`?
