### ISSUE TITLE
replace google groups wirh discourse forum?

### ISSUE THREAD

**Issue by kanishka-work** [jgm/gitit#667]
Also, is this project actively maintained for bug fixes and dependency updates currently? I am debating using it for a project.

**Comment by ickc** [comment]
I believe it is not actively developing anymore but in bug fix only mode for a long time. There were some drastic changes haven't been materialized too.

The actively developing project that this project heavily depends on is pandoc, and pandoc is still using pandoc-discuss, and a few discussions on pandoc-discuss about this topic suggest that it is still going to stick to google groups.

So I don't think there would be any chance for the discussion here moving away from google groups.

**Comment by jgm** [comment]
Correct, the project has been in stable maintenance mode for many years.
For a while I worked on [gitit2](https://github.com/jgm/gitit2) which was a cleaner implementation, but this was never finished, and the original gitit still works reasonably well...
