### ISSUE TITLE
Please replace ConfigFile

### ISSUE THREAD

**Issue by iliastsi** [jgm/gitit#696]
Please replace [ConfigFile](https://hackage.haskell.org/package/ConfigFile) which is unmaintained and doesn't work with GHC 9.6 and newer. We plan on updating GHC on Debian to 9.6, and we cannot build gitit anymore since it depends on ConfigFile. Thanks!

**Comment by jgm** [comment]
I think the simplest approach would be to write a small module in gitit itself that parses the current config file format, which is fairly simple.

**Comment by jgm** [comment]
Another alternative would be to use config-ini, which seems well maintained

**Comment by jgm** [comment]
I've released a new version 0.15.1.2, which does not depend on ConfigFile.

**Comment by iliastsi** [comment]
Thank you @jgm.
